Ajax request for checkin in quickicons - RFC, POC
joomla/backend-template pull request #143
Opened 2019-04-17 16:58 UTC by chmst

Pull Request for Issue #95 .

### Summary of Changes
Some quickicons show the amount of enabled entries in the database. This requires database queries. In case of the checkin icon, all important tables have to be checked which results in duplicate queries is time consuming. 

In this PR an ajax request decouples database queries from the output of the screen. 

Should we use ajax for all icons? It looks strange if the screen shows only spinner icons at the first glance.

2019-04-19 10:39 UTC, brianteeman commented on administrator/components/com_cpanel/tmpl/cpanel/default.php
> +		<?php
why is the col removed?

2019-04-20 15:35 UTC, chmst commented on administrator/components/com_cpanel/tmpl/cpanel/default.php
> +		<?php
My fault - small confusion on my repo,

2019-05-03 08:22 UTC, C-Lodder requested changes

2019-05-03 08:22 UTC, C-Lodder commented on build/media_source/mod_quickicons/js/quickicons.es6.js
> +                elem.innerHTML = response.data;
Don't use `innerHTML` for security reasons

2019-05-03 08:22 UTC, C-Lodder commented on build/media_source/mod_quickicons/js/quickicons.es6.js
> +console.log(elements);
remove `console.log`

2019-05-08 08:50 UTC, chmst commented
Closing this as a new PR follows

2019-05-08 08:50 UTC, closed without merging